---
# tasks file for pubnub-python-tools-ansible-role
- set_fact:
    command: install
  tags: ['never', 'install', 'deploy']

- import_tasks: operations.yml
  tags: ['never', 'install', 'deploy']

- import_tasks: pip/install.yml
  tags: ['never', 'install-pip', 'deploy']

- set_fact:
    command: ppt
  tags: ['never', 'ppt']

- import_tasks: ppt_operations.yml
  tags: ['never', 'ppt']