---
# Run operations based on conditionals

# -t install
# Install MacOS 
- name: Install on OSX type systems
  import_tasks: macOS/install.yml
  when:
  - ansible_os_family == 'Darwin'
  - command == 'install'

# Install Debian
- name: Install on debian type systems
  shell: "echo ubuntu"
  when: 
  - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - command == 'install'

# Install Arch
- name: Install on Archlinux type systems
  shell: "echo arch"
  when: 
  - ansible_distribution == 'arch' or ansible_distribution == 'aarm64'
  - command == 'install'