---
# Run operations based on conditionals

# MacOS 
- name: Install on OSX type systems
  import_tasks: macOS/install.yml
  when: 
  - ansible_distribution == 'MacOSX'
  - command == 'install'  # -t install

# Debian
- name: Install on debian type systems
  sudo: yes
  sudo_user: ubuntu
  when: 
  - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - command == 'install'

# Arch
# Debian
- name: Install on Archlinux type systems
  sudo: yes
  sudo_user: arch
  when: 
  - ansible_distribution == 'arch' or ansible_distribution == 'aarm64'
  - command == 'install'

# All Distributions
# - name: Install pip using python
#   when:
#   - command == 'install'