---
# Run operations based on conditionals

- name: Publish a message using pubnub-python-tools
  shell: "{{ pubnub_virtualenv_path }}/bin/pubnub-python-tools -p {{ space }} -m {{ message_content }}"
  when:
    - command == 'ppt'
    - message_type == 'publish'
  register: publish

- debug:
    var: publish
